import React, {Component} from 'react';
import './index.scss';
import logoImg from '../../assets/logologin.png';

export default class TermsAndConditions extends Component {  
  render() {
    
    return(
      <div className='terms-conditions-zone'>
        <div className="container content-wrapper">        
          <div className="content">

            <div className="text-center title-wrapper">
              <p className='title'>Terms of Use</p>
            </div>
            <div className="body-wrapper">
              <div className='paragraph-wrapper'>
                <p className='text'>Effective date: May 1, 2017</p>
                <p className='text'>Welcome to EnTribe. Please read on to learn the rules and restrictions that govern your use of our website(s), products, services and applications (the “Services”). If you have any questions, comments, or concerns regarding these terms or the Services, please contact us at info@entribe.com.</p>
                <p className='text'>These Terms of Use (the “Terms”) are a binding contract between you and EnTribe, Inc.. (“EnTribe,” “we” and “us”). You must agree to and accept all of the Terms, or you don’t have the right to use the Services. Your using the Services in any way means that you agree to all of these Terms, and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document, as well as those in the Privacy Policy <a href="/policy"> www.entribe.com/policy</a> and Copyright Dispute Policy<a href="#"> www.entribe.com/copyright.</a></p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>Will these Terms ever change?</p>
                <p className='text'>We are constantly trying to improve our Services, so these Terms may need to change along with the Services. We reserve the right to change the Terms at any time, but if we do, we will bring it to your attention by placing a notice on the<a href="#"> www.entribe.com </a> website, by sending you an email, and/or by some other means. </p>
                <p className='text'>If you don’t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes. </p>
                <p className='text'>Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us. </p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>What about my privacy?</p>
                <p className='text'>EnTribe takes the privacy of its users very seriously. For the current EnTribe Privacy Policy, please click here<a href="/policy"> www.entribe.com/policy</a></p>
                <p className='text'>The Children’s Online Privacy Protection Act (“COPPA”) requires that online service providers obtain parental consent before they knowingly collect personally identifiable information online from children who are under 13. We do not knowingly collect or solicit personally identifiable information from children under 13; if you are a child under 13, please do not attempt to register for the Services or send any personal information about yourself to us. If we learn we have collected personal information from a child under 13, we will delete that information as quickly as possible. If you believe that a child under 13 may have provided us personal information, please contact us at alert@entribe.com.</p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>What are the basics of using the Service?</p>
                <p className='text'>You may be required to sign up for an account, and select a password and user name (“EnTribe User ID”). You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your EnTribe User ID a name that you don’t have the right to use, or another person’s name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission.</p>
                <p className='text'>You represent and warrant that you are an individual of legal age to form a binding contract (or if not, you’ve received your parent’s or guardian’s permission to use the Services and gotten your parent or guardian to agree to these Terms on your behalf). </p>
                <p className='text'>You will only use the Services for your own use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws, then you aren’t authorized to use the Services. We can’t and won’t be responsible for your using the Services in a way that breaks the law.</p>
                <p className='text'>You will not share your account or password with anyone, and you must protect the security of your account and your password. You’re responsible for any activity associated with your account.</p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>Your use of the Services is subject to the following additional restrictions:</p>
                <p className='text'>You represent, warrant, and agree that you will not contribute any Content or User Submission (each of those terms is defined below) or otherwise use the Services or interact with the Services in a manner that:</p>
                          <ul className="info">
                              <li>
                                  <p className='text'>(a)  Infringes or violates the intellectual property rights or any other rights (including rights of publicity and personality) of anyone else (including EnTribe);</p>
                              </li>
                              <li>
                                  <p className='text'>(b)  Violates any law or regulation, including, without limitation, any applicable export control laws;</p>
                              </li>
                              <li>
                                  <p className='text'>(c)  Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;</p>
                              </li>
                              <li>
                                  <p className='text'>(d)  Jeopardizes the security of your EnTribe account or anyone else’s (such as allowing someone else to log in to the Services as yo</p>
                              </li>
                              <li>
                                  <p className='text'>(e)  Attempts, in any manner, to obtain the password, account, or other security information from any other user;</p>
                              </li>
                              <li>
                                  <p className='text'>(f)  Violates the security of any computer network, or cracks any passwords or security encryption codes;</p>
                              </li>
                              <li>
                                  <p className='text'>(g)  Runs Maillist, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services’ infrastructure);</p>
                              </li>
                              <li>
                                  <p className='text'>(h)  “Crawls,” “scrapes,” or “spiders” any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);</p>
                              </li>
                              <li>
                                  <p className='text'>(i)  Copies or stores any significant portion of the Content;</p>
                              </li>
                              <li>
                                  <p className='text'>(j)  Decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.</p>
                              </li>
                          </ul>
                          <p className='text'>A violation of any of the foregoing is grounds for termination of your right to use or access the Services.</p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>What are my rights in the Services?</p>
                <p className='text'>The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, User Submissions, and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell, commercialize or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else’s (including EnTribe’s) rights.</p>
                <p className='text'>You understand that EnTribe owns the Services. You won’t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services. </p>
                <p className='text'>The Services may allow you to copy or download certain Content; please remember that just because this functionality exists, doesn’t mean that all the restrictions above don’t apply – they do!</p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>Do I have to grant any licenses to Company or to other users?</p>
                <p className='text'>Anything you post, upload, share, store, or otherwise provide through the Services is your “User Submission.” Some User Submissions are viewable by other users. In order to display your User Submissions on the Services, and to allow other users to enjoy them (where applicable), you grant us certain rights in those User Submissions. Please note that all of the following licenses are subject to our Privacy Policy<a href="#"> www.entribe.com/privacy</a> to the extent they relate to User Submissions that are also your personally-identifiable information. </p>
                <p className='text'>For all User Submissions, you hereby grant EnTribe a license to translate, modify (for technical purposes, for example making sure your content is viewable on an iPhone as well as a computer) and reproduce and otherwise act with respect to such User Submissions, in each case to enable us to operate the Services, as described in more detail below. This is a license only – your ownership in User Submissions is not affected. If you store a User Submission in your own personal EnTribe account, in a manner that is not viewable by any other user except you (a “Personal User Submission”), you grant EnTribe the license above, as well as a license to display, perform, and distribute your Personal User Submission for the sole purpose of making that Personal User Submission accessible to you and providing the Services necessary to do so.</p>
                <p className='text'>If you share a User Submission only in a manner that only certain specified users can view (for example, a private message to one or more other users) (a “Limited Audience User Submission”), then you grant EnTribe the licenses above, as well as a license to display, perform, and distribute your Limited Audience User Submission for the sole purpose of making that Limited Audience User Submission accessible to such other specified users, and providing the Services necessary to do so. Also, you grant such other specified users a license to access that Limited Audience User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services. </p>
                <p className='text'>If you share a User Submission publicly on the Services and/or in a manner that more than just you or certain specified users can view, or if you provide us (in a direct email or otherwise) with any feedback, suggestions, improvements, enhancements, and/or feature requests relating to the Services (each of the foregoing, a “Public User Submission”), then you grant EnTribe the licenses above, as well as a license to display, perform, and distribute your Public User Submission for the purpose of making that Public User Submission accessible to all EnTribe users and providing the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission in connection with the Services and/or otherwise in connection with Company’s businessfor any purpose. Also, you grant all other users of the Services a license to access that Public User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.</p>
                <p className='text'>You agree that the licenses you grant are royalty-free, perpetual, sublicenseable, irrevocable, and worldwide, provided that when you delete your EnTribe account, we will stop displaying your User Submissions (other than Public User Submissions, which may remain fully available) to other users (if applicable), but you understand and agree that it may not be possible to completely delete that content from EnTribe’s records, and that your User Submissions may remain viewable elsewhere to the extent that they were copied or stored by other users. </p>
                <p className='text'>Furthermore, in consideration of EnTribe’s provision of the Services to you and other valuable consideration, the receipt of which is hereby acknowledged, you hereby give EnTribe, its employees, contractors, and agents, and its assigns, licensees, successors in interest, legal representatives, and heirs the irrevocable right to use and disseminate throughout the world in perpetuity your name (or any fictional name), picture, portrait, photograph, video and/or likeness in all forms and in all manners and media now known or hereafter invented (your “Likeness”) to the extent your Likeness is contained in your User Submissions, without any restriction as to changes or alterations (including but not limited to composite or distorted representations or derivative works of your Likeness made in any medium) for advertising, trade, promotion, exhibition, or any other lawful purposes in connection with EnTribe’s business, products and/or services. You hereby waive any right to inspect or approve any intermediary version(s) or finished version(s) of the results of the use of your Likeness (“Results”). You hereby release and agree to hold harmless EnTribe, its assigns, successors in interest, licensees, legal representatives and heirs from any liability by virtue of any blurring, distortion, alteration, optical illusion, or use of your Likeness that may occur or be produced in the creation of the Results. You hereby waive any claims you may have based on any usage of the Results or works derived therefrom, including but not limited to claims for either invasion of privacy, publicity or libel.</p>
                <p className='text'>Finally, you understand and agree that EnTribe, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media, and the foregoing licenses include the rights to do so.</p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>What if I see something on the Services that infringes my copyright?</p>
                <p className='text'>You may have heard of the Digital Millennium Copyright Act (the “DMCA”), as it relates to online service providers, like EnTribe, being asked to remove material that allegedly violates someone’s copyright. We respect others’ intellectual property rights, and we reserve the right to delete or disable Content alleged to be infringing, and to terminate the accounts of repeat alleged infringers; to review our complete Copyright Dispute Policy and learn how to report potentially infringing content, click here <a href="#"> www.entribe.com/copyright. </a> To learn more about the DMCA, click here [link to <a href="#">http://www.copyright.gov/legislation/dmca.pdf.</a> </p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>Who is responsible for what I see and do on the Services?</p>
                <p className='text'>Any information or content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such content originated, and you access all such information and content at your own risk, and we aren’t liable for any errors or omissions in that information or content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can’t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services. </p>
                <p className='text'>You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services.</p>
                <p className='text'>The Services may contain links or connections to third party websites or services that are not owned or controlled by EnTribe. When you access third party websites or use third party services, you accept that there are risks in doing so, and that EnTribe is not responsible for such risks. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third party website or service that you visit or utilize. </p>
                <p className='text'>EnTribe has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third party websites or by any third party that you interact with through the Services. In addition, EnTribe will not and cannot monitor, verify, censor or edit the content of any third party site or service. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third party website or service</p>
                <p className='text'>Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that EnTribe shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.</p>
                <p className='text'>If there is a dispute between participants on this site, or between users and any third party, you agree that EnTribe is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release EnTribe, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor."</p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>Will EnTribe ever change the Services?</p>
                <p className='text'>We’re always trying to improve the Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We’ll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn’t always practical. Similarly, we reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice. </p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>Do the Services cost anything?</p>
                <p className='text'>The EnTribe Services are currently free, but we reserve the right to charge for certain or all Services in the future. We will notify you before any Services you are then using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services.</p>
                </div>
              <div className='paragraph-wrapper'>
                <p className='header'>What if I want to stop using the Services?</p>
                <p className='text'>You’re free to do that at any time, by contacting us at contact@entribe.com; please refer to our Privacy Policy <a href="/policy"> www.entribe.com/policy, </a> as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services. </p>
                <p className='text'>EnTribe is also free to terminate (or suspend access to) your use of the Services or your account, for any reason in our discretion, including your breach of these Terms. EnTribe has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.</p>
                <p className='text'>Account termination may result in destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account. We will try to provide advance notice to you prior to our terminating your account so that you are able to retrieve any important User Submissions you may have stored in your account (to the extent allowed by law and these Terms), but we may not do so if we determine it would be impractical, illegal, not in the interest of someone’s safety or security, or otherwise harmful to the rights or property of EnTribe.</p>
                <p className='text'>If you have deleted your account by mistake, contact us immediately at<b> [insert means]</b> – we will try to help, but unfortunately, we can’t promise that we can recover or restore anything.</p>
                <p className='text'>Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us. </p>
              </div>
              <div className='paragraph-wrapper'>
                <p className='header'>What else do I need to know?</p>
                <p className='text'><i>Warranty Disclaimer.</i> Neither EnTribe nor its licensors or suppliers make any representations or warranties concerning any content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services. We (and our licensors and suppliers) make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services. [Products and services purchased or offered (whether or not following such recommendations and suggestions) through the Services are provided “AS IS” and without any warranty of any kind from Company or others (unless, with respect to such others only, provided expressly and unambiguously in writing by a designated third party for a specific product).] THE SERVICES AND CONTENT ARE PROVIDED BY ENTRIBE (AND ITS LICENSORS AND SUPPLIERS) ON AN “AS-IS” BASIS, WITHOUT WARRANTIES OR ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. </p>
                <p className='text'><i>Limitation of Liability.</i> TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL ENTRIBE (OR ITS LICENSORS OR SUPPLIERS) BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, OR (B) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF $100 OR (II) ANY MATTER BEYOND OUR REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU. </p>
                <p className='text'><i>Indemnity.</i> To the fullest extent allowed by applicable law, You agree to indemnify and hold EnTribe, its affiliates, officers, agents, employees, and partners harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys’ fees) arising from or in any way related to any third party claims relating to (a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of these Terms. [In the event of such a claim, suit, or action (“Claim”), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder).</p>
                <p className='text'><i>Assignment. </i> You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without EnTribe’s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.</p>
                <p className='text'><i>Choice of Law; Arbitration.</i> These Terms are governed by and will be construed under the laws of the State of California, without regard to the conflicts of laws provisions thereof. Any dispute arising from or relating to the subject matter of these Terms shall be finally settled in San Francisco County, California, in English, in accordance with the Streamlined Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, Inc. ("JAMS") then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of JAMS arbitrators in accordance with such Rules. Judgment upon the award rendered by such arbitrator may be entered in any court of competent jurisdiction. Notwithstanding the foregoing obligation to arbitrate disputes, each party shall have the right to pursue injunctive or other equitable relief at any time, from any court of competent jurisdiction. For all purposes of this Agreement, the parties consent to exclusive jurisdiction and venue in the state or federal courts located in, respectively, San Francisco County, California, or the Northern District of California. Any arbitration under these Terms will take place on an individual basis: class arbitrations and class actions are not permitted. YOU UNDERSTAND AND AGREE THAT BY ENTERING INTO THESE TERMS, YOU AND ENTRIBE ARE EACH WAIVING THE RIGHT TO TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.</p>
                <p className='text'><i>Miscellaneous.</i> You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that the EnTribe may, in its sole discretion, do any of the foregoing on your behalf or for itself as it sees fit. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and EnTribe agree that these Terms are the complete and exclusive statement of the mutual understanding between you and EnTribe, and that it supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms,. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of EnTribe, and you do not have any authority of any kind to bind EnTribein any respect whatsoever. </p>
                <p className='text'>You and EnTribe agree there are no third party beneficiaries intended under these Terms.</p>
              </div>
            </div>
            
          </div>
        </div>
      </div>
    )
  }
}