export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAIL = 'GET_DASHBOARD_FAIL';
export const GET_BILL = 'GET_BILL';
export const GET_BILL_SUCCESS = 'GET_BILL_SUCCESS';
export const GET_BILL_FAIL = 'GET_BILL_FAIL';