export const UPLOAD_WIDGET = 'UPLOAD_WIDGET';
export const UPLOAD_WIDGET_SUCCESS = 'UPLOAD_WIDGET_SUCCESS';
export const UPLOAD_WIDGET_FAIL = 'UPLOAD_WIDGET_FAIL';

export const CHECK_EMAIL = 'CHECK_EMAIL';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAIL = 'CHECK_EMAIL_FAIL';

export const CHANGE_LINK = 'CHANGE_LINK';
export const CHANGE_LINK_SUCCESS = 'CHANGE_LINK_SUCCESS';
export const CHANGE_LINK_FAIL = 'CHANGE_LINK_FAIL';

export const REGISTER_WIDGET = 'REGISTER_WIDGET';
export const REGISTER_WIDGET_SUCCESS = 'REGISTER_WIDGET_SUCCESS';
export const REGISTER_WIDGET_FAIL = 'REGISTER_WIDGET_FAIL';